export const translations = {
  en: {
    // General
    dashboard: 'Dashboard',
    claims: 'Claims',
    payment: 'Payment',
    policy: 'My Policy',
    riskMap: 'Risk Map',
    logout: 'Logout',
    login: 'Login',
    signup: 'Sign Up',
    loading: 'Loading...',
    error: 'Error',
    // Dashboard
    goodMorning: 'Good Morning',
    activeConditions: 'Active Conditions',
    coverageEstimate: "Today's Coverage Estimate",
    workAdvisor: 'Work Advisor',
    zoneCond: 'Zone Conditions',
    yourPlan: 'Your Plan',
    recentClaims: 'Recent Claims',
    weeklyPremium: 'Weekly Premium',
    premiumBreakdown: 'Premium Breakdown',
    basePremium: 'Base Premium',
    metroBonus: 'Metro City Modifier',
    safetyBonus: '7-Day Safety Modifier',
    shiftBonus: 'Night Shift Modifier',
    final: 'Final Premium',
    nightShift: 'Night Shift',
    yes: 'Yes',
    no: 'No',
    // Payment
    paymentDue: 'Payment Due',
    gracePeriod: 'Grace Period',
    frozen: 'Account Frozen',
    active: 'Active',
    payNow: 'Pay Now ₹',
    dueDate: 'Due Date',
    graceDeadline: 'Grace Deadline',
    paymentHistory: 'Payment History',
    payNowDesc: 'Click to simulate weekly premium payment',
    frozenWarning: 'Your account is frozen. Pay your premium to reactivate.',
    graceWarning: 'Grace period ending soon. Pay to avoid account freeze.',
    dueWarning: 'Payment is overdue. You have a grace period.',
    // Claims
    fileClaim: 'File a Claim',
    noClaim: 'No eligible disruption events in your zone',
    claimEligible: 'Claim Eligible',
    claimNotEligible: 'Not Eligible (No Overlap)',
    overlapHours: 'Overlap Hours',
    yourShift: 'Your Shift',
    disruptionWindow: 'Disruption Window',
    disruptionFactor: 'Disruption Factor',
    payoutFormula: 'Payout Formula',
    // Admin
    overview: 'Overview',
    zoneAnalytics: 'Zone Analytics',
    workers: 'Workers',
    // Auth
    enterEmail: 'Enter email',
    enterPassword: 'Enter password',
    workerPortal: 'Worker Portal',
    adminPortal: 'Admin Portal',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    allClear: 'All clear',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    claims: 'दावे',
    payment: 'भुगतान',
    policy: 'मेरी पॉलिसी',
    riskMap: 'जोखिम मानचित्र',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    signup: 'साइन अप',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    goodMorning: 'नमस्ते',
    activeConditions: 'सक्रिय स्थितियां',
    coverageEstimate: 'आज का कवरेज अनुमान',
    workAdvisor: 'कार्य सलाहकार',
    zoneCond: 'जोन की स्थिति',
    yourPlan: 'आपकी योजना',
    recentClaims: 'हाल के दावे',
    weeklyPremium: 'साप्ताहिक प्रीमियम',
    premiumBreakdown: 'प्रीमियम विवरण',
    basePremium: 'आधार प्रीमियम',
    metroBonus: 'मेट्रो शहर संशोधक',
    safetyBonus: '7-दिन सुरक्षा संशोधक',
    shiftBonus: 'रात की पाली संशोधक',
    final: 'अंतिम प्रीमियम',
    nightShift: 'रात की पाली',
    yes: 'हाँ',
    no: 'नहीं',
    paymentDue: 'भुगतान देय',
    gracePeriod: 'रियायत अवधि',
    frozen: 'खाता फ्रीज',
    active: 'सक्रिय',
    payNow: 'अभी भुगतान करें ₹',
    dueDate: 'देय तारीख',
    graceDeadline: 'अंतिम तारीख',
    paymentHistory: 'भुगतान इतिहास',
    payNowDesc: 'साप्ताहिक प्रीमियम भुगतान करने के लिए क्लिक करें',
    frozenWarning: 'आपका खाता फ्रीज है। प्रीमियम चुकाएं।',
    graceWarning: 'रियायत अवधि समाप्त होने वाली है।',
    dueWarning: 'भुगतान अतिदेय है।',
    fileClaim: 'दावा दर्ज करें',
    noClaim: 'आपके क्षेत्र में कोई सक्रिय व्यवधान नहीं',
    claimEligible: 'दावे के योग्य',
    claimNotEligible: 'योग्य नहीं (कोई ओवरलैप नहीं)',
    overlapHours: 'ओवरलैप घंटे',
    yourShift: 'आपकी पाली',
    disruptionWindow: 'व्यवधान समय',
    disruptionFactor: 'व्यवधान कारक',
    payoutFormula: 'भुगतान सूत्र',
    overview: 'अवलोकन',
    zoneAnalytics: 'जोन विश्लेषण',
    workers: 'कर्मचारी',
    enterEmail: 'ईमेल दर्ज करें',
    enterPassword: 'पासवर्ड दर्ज करें',
    workerPortal: 'वर्कर पोर्टल',
    adminPortal: 'एडमिन पोर्टल',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    allClear: 'सब साफ',
  }
}

export function t(lang, key) {
  return translations[lang]?.[key] || translations.en[key] || key
}
